nmMode: hardlinks-local

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  webpack@*:
    dependencies:
      lodash: "^4.17.21"
      axios-mock-adapter: "1.10.0"
      

yarnPath: .yarn/releases/yarn-berry.cjs
