nmMode: hardlinks-local

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  webpack@*:
    dependencies:
      lodash: "^4.17.21"
      axios-mock-adapter: "1.10.0"
      swiper: "6.8.4"
      react-toastify: "8.1.0"
      react-daum-postcode: "^3.0.1"
      react-loader-spinner: "^6.0.0-0"
  react-scripts@*:
    dependencies:
      "sass-loader": "*" 
    peerDependencies:
      "sass": "*" 
  styled-components@*:
    dependencies:
      react-is: "*"    
      

yarnPath: .yarn/releases/yarn-berry.cjs
